### ISSUE TITLE
Deleting data

### ISSUE THREAD

**Issue by Dragons788** [SkyCraft78/skript-storage#5]
How do I delete a section? How do I delete all the data within First:?
Example:
```
First:
    Second: 1
    Third:
        Forth: 2
```
